tap "homebrew/bundle"
cask "android-studio"
cask "betterdisplay"
cask "hammerspoon"
cask "intellij-idea-ce"
cask "libreoffice"
cask "steam"
cask "utm"
cask "vorta"
cask "whisky"
mas "Outlanders", id: 1468558187
mas "Xcode", id: 497799835
vscode "lfs.vscode-emacs-friendly"
vscode "ms-vscode.live-server"
