tap "homebrew/bundle"
cask "betterdisplay"
cask "intellij-idea-ce"
cask "key-codes"
cask "porting-kit"
cask "vorta"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
vscode "continue.continue"
vscode "lfs.vscode-emacs-friendly"
vscode "ms-vscode-remote.remote-containers"
vscode "vscode-icons-team.vscode-icons"
